require "minitest/autorun"

require_relative File.join('..', 'setup')

describe "Filename" do

  # https://docs.google.com/spreadsheets/d/1KJ3bmt1csh_zfdnxMHveVQKlVgu0Ww78XuhaeFWAg0I/edit#gid=1380526985&range=B3
  TEST_DATA = [
    [ 7971, '########_######.jpg', '20230526_203003.jpg', '%Y%m%d', '_', '%H%M%S', '(?i)(\d{8}_\d{6}).jpg'],
    [ 6709, 'img_####.jpg', 'IMG_0320.jpg', '', '', '', ''],
    [ 2133, '####-##-## ##.##.##.jpg', '2017-09-03 11.42.08.jpg', '%Y-%m-%d', 'space', '%H.%M.%S', '(?i)(\d{4}-\d{2}-\d{2} \d{1,2}\.\d{2}\.\d{2})(?:-\d+|-Pano)?.(?:jpg|png|mp4|dng)'],
    [ 1061, 'dsc#####.jpg', 'DSC04187.jpg', '', '', '', ''],
    [ 1005, 'imgp####.jpg', 'IMGP3883.JPG', '', '', '', ''],
    [  990, 'p#######.jpg', 'P4154179.JPG', '', '', '', ''],
    [  980, 'dsc_####.jpg', 'DSC_0148.JPG', '', '', '', ''],
    [  953, 'img-########-wa####.jpg', 'IMG-20230430-WA0074.jpg', '%Y%m%d', '', '', '(?i)IMG-(\d{8})-WA\d+.jpe?g'],
    [  797, '########_######_hdr.jpg', '20160403_113354_HDR.jpg', '%Y%m%d', '_', '%H%M%S', '(?i)(\d{8}_\d{6})_HDR.jpg'],
    [  687, 'dscf####.jpg', 'DSCF0890.JPG', '', '', '', ''],
    [  682, 'img_####.heic', 'IMG_0319.HEIC', '', '', '', ''],
    [  504, '########.jpg', '19730019.JPG', '', '', '', ''],
    [  419, '########-#.jpg', '00000076-2.JPG', '', '', '', ''],
    [  379, '########_######.mp#', '20230525_190151.mp4', '%Y%m%d', '_', '%H%M%S', '(?i)(\d{8}_\d{6})(?:_\d+)?.(?:mp4|heic)'],
    [  347, 'pc######.jpg', 'PC250376.JPG', '', '', '', ''],
    [  338, '####-##-## ##.##.##-#.jpg', '2017-09-03 11.42.09-5.jpg', '%Y-%m-%d', 'space', '%H.%M.%S', '(?i)(\d{4}-\d{2}-\d{2} \d{1,2}\.\d{2}\.\d{2})(?:-\d+|-Pano)?.(?:jpg|png|mp4|dng)'],
    [  252, 'img_########_######.jpg', 'IMG_20221007_103823.jpg', '%Y%m%d', '_', '%H%M%S', '(?i)IMG_(\d{8}_\d{6}).jpg'],
    [  246, 'fsl_####.jpg', 'FSL_2438.JPG', '', '', '', ''],
    [  233, 'img-########-wa####.jpeg', 'IMG-20230510-WA0007.jpeg', '%Y%m%d', '', '', '(?i)IMG-(\d{8})-wa\d+.jpe?g'],
    [  201, 'f#######.jpg', 'f0628376.jpg', '', '', '', ''],
    [  193, '####-##-## ##.##.##.png', '2017-03-12 03.08.52.png', '%Y-%m-%d', 'space', '%H.%M.%S', '(?i)(\d{4}-\d{2}-\d{2} \d{1,2}\.\d{2}\.\d{2})(?:-\d+|-Pano)?.(?:jpg|png|mp4|dng)'],
    [  132, '####-##-## ##.##.##.mp#', '2019-10-27 14.21.44.mp4', '%Y-%m-%d', 'space', '%H.%M.%S', '(?i)(\d{4}-\d{2}-\d{2} \d{1,2}\.\d{2}\.\d{2})(?:-\d+|-Pano)?.(?:jpg|png|mp4|dng)'],
    [  125, 'dsc#####.arw', 'DSC04170.ARW', '', '', '', ''],
    [   99, 'mouth.## (desktop-c#qnt#d\'s conflicted copy ####-##-##).png', 'mouth.65 (DESKTOP-C2QNT8D\'s conflicted copy 2023-02-07).png', '', '', '', ''],
    [   85, 'gfx_eq_b#_#_jt_tiny.##.png', 'GFX_EQ_b1_1_jt_tiny.94.png', '', '', '', ''],
    [   81, '########-dsc_####.jpg', '20120731-DSC_6052.jpg', '%Y%m%d', '', '', '(?i)(\d{8})-DSC_\d{4}.jpg'],
    [   78, '########_######.heic', '20200409_211937.heic', '%Y%m%d', '_', '%H%M%S', '(?i)(\d{8}_\d{6})(?:_\d+)?.(?:mp4|heic)'],
    [   74, '##.jpg', '58.jpg', '', '', '', ''],
    # [   72, '########_######_##.mp#', '20220903_234858_99.mp4', '%Y%m%d', '_', '%H%M%S', '(?i)(\d{8}_\d{6})(?:_\d+)?.(?:mp4|heic)'],
    # [   64, 'img_####.mov', 'IMG_9068.MOV', '', '', '', ''],
    # [   62, '####-##-## ##.##.##-pano.dng', '2017-09-15 13.33.30-Pano.dng', '%Y-%m-%d', 'space', '%H.%M.%S', '(?i)(\d{4}-\d{2}-\d{2} \d{1,2}\.\d{2}\.\d{2})(?:-\d+|-Pano)?.(?:jpg|png|mp4|dng)'],
    # [   61, 'eyes_v##.## (desktop-c#qnt#d\'s conflicted copy ####-##-##).jpg', 'eyes_v01.95 (DESKTOP-C2QNT8D\'s conflicted copy 2023-02-07).jpg', '', '', '', ''],
    # [   60, 'img_####-#.jpg', 'IMG_0818-2.jpg', '', '', '', ''],
    # [   58, '##_###x###.png', '20_256x256.png', '', '', '', ''],
    # [   56, 'screen shot ####-##-## at ##.##.##.png', 'Screen Shot 2022-09-12 at 10.53.12.png', '%Y-%m-%d', 'at', '%H.%M.%S', '(?i)(?:Screen Shot )?(\d{4}-\d{2}-\d{2} at \d{1,2}\.\d{2}\.\d{2})(?:-\d+)?.(?:png)'],
    # [   54, 'cimg####.jpg', 'CIMG1487.jpg', '', '', '', ''],
    # [   54, 'screenshot_########-######.png', 'Screenshot_20171214-154300.png', '%Y%m%d', '-', '%H%M%S', ''],
    # [   53, 'gopr####.jpg', 'GOPR2546.JPG', '', '', '', ''],
    # [   53, 'vid-########-wa####.mp#', 'VID-20230126-WA0000.mp4', '%Y%m%d', '', '', ''],
    # [   46, 'whatsapp image ####-##-## at #.##.## pm.jpeg', 'WhatsApp Image 2023-04-15 at 6.41.07 PM.jpeg', '%Y-%m-%d', 'at', '%H.%M.%S %p', '(?i)(?:WhatsApp Image )?(\d{4}-\d{2}-\d{2} at \d{1,2}\.\d{2}\.\d{2} (?:PM|AM))(?:-\d+)?.(?:png|jpeg)'],
    # [   45, 'thumbnail.jpg', 'Thumbnail.jpg', '', '', '', ''],
    # [   43, '##########-##.jpg', '1523059275-16.jpg', '', '', '%s', '(?i)(\d{10})-(?:\d+).jpg'],
    # [   43, 'imgp####.pef', 'IMGP3814.PEF', '', '', '', ''],
    # [   41, '########_######-#.jpg', '20220115_173159-2.jpg', '%Y%m%d', '_', '%H%M%S', '(?i)(\d{8}_\d{6})(?:[_-]\d+)?.(?:mp4|heic|jpg)'],
    # [   40, 'img_####.dng', 'IMG_1093.dng', '', '', '', ''],
    # [   39, 'picture #.png', 'Picture 4.png', '', '', '', ''],
    # [   37, '##-##.png', '02-01.png', '', '', '', ''],
    # [   36, 'p#######.mov', 'P8134268.MOV', '', '', '', ''],
    # [   35, '####-##-##-#.jpg', '2015-10-23-5.jpg', '%Y-%m-%d', '', '', '(?i)(\d{4}-\d{2}-\d{2})(?:-\d+).jpg'],
    # [   34, '##########-#.jpg', '1523035601-2.jpg', '', '', '%s', '(?i)(\d{10})-(?:\d+).jpg'],
    # [   33, 'sugarloaf##.jpg', 'sugarloaf18.jpg', '', '', '', ''],
    # [   32, '########_######_###.jpg', '20230113_152749_001.jpg', '%Y%m%d', '_', '%H%M%S', ''],
    # [   31, 'mvi_####.mov', 'MVI_0117.MOV', '', '', '', ''],
    # [   31, 'st#-#.tiff', 'st1-4.tiff', '', '', '', ''],
    # [   31, 'st#.tiff', 'st0.tiff', '', '', '', ''],
    # [   30, '#march####-##.png', '4march2015-30.png', '%-d%B%Y', '', '', ''],
    # [   30, 'carrie furnace ##.jpg', 'Carrie Furnace 29.jpg', '', '', '', ''],
    # [   30, 'img_####_#_#_tonemapped.jpg', 'IMG_3825_6_7_tonemapped.jpg', '', '', '', ''],
    # [   30, 'whatsapp image ####-##-## at ##.##.##.jpeg', 'WhatsApp Image 2019-08-19 at 21.32.01.jpeg', '%Y-%m-%d', 'at', '%H.%M.%S', ''],
    # [   29, '########_######-pano.dng', '20200725_171234-Pano.dng', '%Y%m%d', '_', '%H%M%S', ''],
    # [   29, '##-##.jpg', '05-31.jpg', '', '', '', ''],
    # [   29, 'scan_########_##.jpg', 'Scan_20190606_34.jpg', '', '', '', ''],
    # [   28, 'gopr#### copy.jpg', 'GOPR1195 copy.JPG', '', '', '', ''],
    # [   27, 'img_########_######_###.jpg', 'IMG_20221104_212700_703.jpg', '%Y%m%d', '_', '%H%M%S', ''],
    # [   27, 'photo ##-##-#### ## ## ##.jpg', 'Photo 25-03-2015 14 22 51.jpg', '%d-%m-%Y', 'space', '%H %M %S', ''],
    # [   26, 'dorm##.jpg', 'dorm82.jpg', '', '', '', ''],
    # [   23, '########_######_##.jpg', '20220903_234858_01.jpg', '%Y%m%d', '_', '%H%M%S', ''],
    # [   23, 'core-################-##.jpg', 'core-1524646984163049-34.jpg', '', '', '%s%6N', ''],
    # [   23, 'screenshot_########-######.jpg', 'Screenshot_20220822-190552.jpg', '%Y%m%d', '-', '%H%M%S', ''],
    # [   22, '########_######(#).jpg', '20221118_220707(0).jpg', '%Y%m%d', '_', '%H%M%S', ''],
    # [   22, '###.jpg', '118.jpg', '', '', '', ''],
    # [   19, '########-r#######.jpg', '20220226-R0006029.jpg', '%Y%m%d', '', '', ''],
    # [   19, 'droppedimage-##.tiff', 'droppedImage-35.tiff', '', '', '', ''],
    # [   19, 'screenshot_####-##-##-##-##-##.png', 'Screenshot_2016-03-05-07-39-08.png', '%Y-%m-%d', '-', '%H-%M-%S', ''],
    # [   19, 'whatsapp image ####-##-## at #.##.## pm (#).jpeg', 'WhatsApp Image 2020-03-14 at 6.14.03 PM (1).jpeg', '%Y-%m-%d', 'at', '%l.%M.%S %p', ''],
    # [   18, 'burn_iris##.tif', 'burn_iris00.tif', '', '', '', ''],
    # [   17, '####-##-##.jpg', '2017-05-18.jpg', '%Y-%m-%d', '', '', ''],
    # [   17, 'dixmont ##.jpg', 'Dixmont 17.jpg', '', '', '', ''],
    # [   17, 'gh######.mp#', 'GH012580.MP4', '', '', '', ''],
    # [   16, '####-##-##-##.jpg', '2017-08-25-13.jpg', '%Y-%m-%d', '', '', ''],
    # [   15, '####-##-##-##-##.jpg', '2017-09-15-22-40.jpg', '%Y-%m-%d', '-', '%H-%M', ''],
    # [   14, '####-##-##-######.jpg', '2023-05-23-174617.jpg', '%Y-%m-%d', '', '%H%M%S', ''],
    # [   14, '#.##.## ###.jpg', '3.19.06 015.jpg', '%-m.%-d.%y', '', '', ''],
    # [   13, '####-##-## ##.##.##-#.mp#', '2017-09-03 11.29.57-6.mp4', '%Y-%m-%d', 'space', '%H.%M.%S', ''],
    # [   13, 'screen shot ####-##-## at #.##.## pm.png', 'Screen Shot 2017-05-05 at 5.28.32 PM.png', '%Y-%m-%d', 'at', '%l.%M.%S %p', ''],
    # [   12, '########_######_burst##.jpg', '20160305_150955_Burst01.jpg', '%Y%m%d', '_', '%H%M%S', ''],
    # [   12, 'burn_anim##.tif', 'burn_anim00.tif', '', '', '', ''],
    # [   12, 'g#######.jpg', 'G0042562.JPG', '', '', '', ''],
    # [   12, 'img_####.m#v', 'IMG_6970.m4v', '', '', '', ''],
    # [   12, 'img_####.mp#', 'IMG_4614.mp4', '', '', '', ''],
    # [   12, 'img_####_#_#_fused.jpg', 'IMG_4070_1_2_fused.jpg', '', '', '', ''],
    # [   12, 'imgp####-#.jpg', 'IMGP3509-2.JPG', '', '', '', ''],
    # [   12, 'scan_########_#-#-#.jpg', 'Scan_20190606_6-2-2.jpg', '%Y%m%d', '', '', ''],
    # [   12, 'scan_########_#-#.jpg', 'Scan_20190606_6-2.jpg', '%Y%m%d', '', '', ''],
    # [   11, '########-##.jpg', '00000001-10.JPG', '', '', '', ''],
    # [   11, 'mirror##.jpg', 'mirror17.jpg', '', '', '', ''],
    # [   11, 'screen shot ####-##-## at ##.##.## am.png', 'Screen Shot 2015-01-16 at 11.00.06 AM.png', '%Y-%m-%d', 'at', '%l.%M.%S %p', ''],
    # [   11, 'screenshot_########-######_chrome.jpg', 'Screenshot_20220815-190823_Chrome.jpg', '%Y%m%d', '-', '%H%M%S', ''],
    # [   10, 'badge_lvl_##.png', 'badge_lvl_90.png', '', '', '', ''],
    # [   10, 'google-accounts-#.png', 'google-accounts-9.png', '', '', '', ''],
    # [   10, 'photo #-##-##, ## ## ## pm.png', 'Photo 9-20-12, 11 54 20 PM.png', '', '', '', ''],
    # [   10, 'vid_########_######.mp#', 'VID_20221104_202629.mp4', '%Y%m%d', '_', '%H%M%S', ''],
    # [    9, '########_######-pano.jpg', '20220709_174355-PANO.jpg', '%Y%m%d', '_', '%H%M%S', ''],
    # [    9, 'award #.jpeg', 'award 9.jpeg', '', '', '', ''],
    # [    9, 'core-################-#.jpg', 'core-1530441248256673-8.jpg', '', '', '%s%6N', ''],
    # [    9, 'dji_########_######_##.jpg', 'DJI_20230518_205137_45.jpg', '%Y%m%d', '_', '%H%M%S', ''],
    # [    9, 'esop-plan-#.png', 'esop-plan-9.png', '', '', '', ''],
    # [    9, 'gfx_eq_b#_#_jt_tiny.#.png', 'GFX_EQ_b1_1_jt_tiny.1.png', '', '', '', ''],
    # [    9, 'img_####_##_##_tonemapped.jpg', 'IMG_1989_90_91_tonemapped.jpg', '', '', '', ''],
    # [    9, 'meet-the-boss-#.png', 'meet-the-boss-9.png', '', '', '', ''],
    # [    9, 'mindshare-#.png', 'mindshare-9.png', '', '', '', ''],
    # [    9, 'office #.jpeg', 'office 8.jpeg', '', '', '', ''],
    # [    9, 'photo ##-#-##, ## ## ## am.png', 'Photo 10-5-12, 11 20 03 AM.png', '%d-%m-%Y', ',space', '%l.%M.%S %p', ''],
    # [    9, 'photo on ####-##-## at ##.##.jpg', 'Photo on 2011-07-30 at 14.26.jpg', 'y', '', 'y', ''],
    # [    9, 'screenshot_########-######_wechat.jpg', 'Screenshot_20180728-150430_WeChat.jpg', 'y', '', '', ''],
    # [    9, 'whatsapp image ####-##-## at ##.##.## pm.jpeg', 'WhatsApp Image 2020-03-14 at 10.43.24 PM.jpeg', 'y', '', 'y', ''],
    # [    8, '#.jpg', '9.jpg', '', '', '', ''],
    # [    8, 'akamai-mapping-#.png', 'akamai-mapping-8.png', '', '', '', ''],
    # [    8, 'bbg-################-#.jpg', 'bbg-1532835660948159-2.jpg', 'y', '', 'y', ''],
    # [    8, 'bg#.jpg', 'Bg4.jpg', '', '', '', ''],
    # [    8, 'cape#.jpg', 'cape4.jpg', '', '', '', ''],
    # [    8, 'finance-####-##-##-#.png', 'finance-2022-08-05-9.png', 'y', '', '', ''],
    # [    8, 'graduation#.jpg', 'graduation1.jpg', '', '', '', ''],
    # [    8, 'photo ##.jpg', 'Photo 15.jpg', '', '', '', ''],
    # [    8, 'photo #.jpg', 'Photo 1.jpg', '', '', '', ''],
    # [    8, 'photo on #-##-## at #.## am.jpg', 'Photo on 4-19-14 at 9.24 AM.jpg', 'y', '', 'y', ''],
    # [    8, 'reference-#.png', 'reference-9.png', '', '', '', ''],
    # [    8, 'scan_########_#.jpg', 'Scan_20190606_6.jpg', 'y', '', '', ''],
    # [    8, 'screen shot ####-##-## at ##.##.## pm.png', 'Screen Shot 2016-01-25 at 12.10.44 PM.png', 'y', '', 'y', ''],
    # [    8, 'screenshot_########-######_whatsapp.jpg', 'Screenshot_20220825-174303_WhatsApp.jpg', 'y', '', 'y', ''],
    # [    8, 'st#-##.tiff', 'st0-17.tiff', '', '', '', ''],
    # [    8, 'success story-##.jpg', 'Success story-01.jpg', '', '', '', ''],
    # [    8, 'thinkstockphotos-#########.jpg', 'ThinkstockPhotos-481694274.jpg', '', '', '', ''],
    # [    7, '########_######_pano.jpg', '20160305_122005_Pano.jpg', 'y', '', 'y', ''],
    # [    7, 'ann bowdoin ##.jpg', 'Ann Bowdoin 06.jpg', '', '', '', ''],
    # [    7, 'bahasa indonesia #.png', 'Bahasa Indonesia 5.png', '', '', '', ''],
    # [    7, 'e#-fa karir.com-march####.jpg', 'e7-FA karir.com-March2015.jpg', 'y', '', '', ''],
    # [    7, 'finance-####-##-##-##.png', 'finance-2022-08-05-16.png', 'y', '', '', ''],
    # [    7, 'gopr#### copy.mp#', 'GOPR1122 copy.MP4', '', '', '', ''],
    # [    7, 'image.png', 'image.png', '', '', '', ''],
    # [    7, 'img_########_#######.jpg', 'IMG_20160831_2325227.jpg', 'y', '', 'y', ''],
    # [    7, 'update-nov-####-#.png', 'update-nov-2022-7.png', '', '', '', ''],
    # [    7, 'view applicant #-#.jpg', 'View Applicant 2-2.jpg', '', '', '', ''],
    # [    7, 'woods##.jpg', 'woods41.jpg', '', '', '', ''],
    # [    6, '########_######-smaller.jpg', '20220903_234943-smaller.jpg', 'y', '', 'y', ''],
    # [    6, '####-##-## ##.##.##-edit.jpg', '2017-08-25 10.48.13-Edit.jpg', 'y', '', 'y', ''],
    # [    6, '####-##-##-img_####.jpg', '2013-07-04-IMG_0562.jpg', 'y', '', '', ''],
    # [    6, '##-diagnosis-#.jpg', '40-diagnosis-5.jpg', '', '', '', ''],
    # [    6, '##-img_####.jpg', '17-IMG_3735.jpg', '', '', '', ''],
    # [    6, 'dsc_#### #x#.jpg', 'DSC_0148 4x6.jpg', '', '', '', ''],
    # [    6, 'faces#.png', 'faces1.png', '', '', '', ''],
    # [    6, 'favicon.ico', 'favicon.ico', '', '', '', ''],
    # [    6, 'google-login-#.png', 'google-login-7.png', '', '', '', ''],
    # [    6, 'hot air#.jpg', 'hot air6.jpg', '', '', '', ''],
    # [    6, 'img_####.png', 'IMG_4209.PNG', '', '', '', ''],
    # [    6, 'pb######.jpg', 'PB060353.JPG', '', '', '', ''],
    # [    6, 'pc######.mov', 'PC313829.MOV', '', '', '', ''],
    # [    6, 'salary benchmark #.jpg', 'Salary Benchmark 3.jpg', '', '', '', ''],
    # [    6, 'sanny ##.jpg', 'Sanny 03.jpg', '', '', '', ''],
    # [    6, 'screenshot from ####-##-## ##-##-##.png', 'Screenshot from 2023-03-10 17-12-55.png', 'y', '', 'y', ''],
    # [    6, 'screenshot_########-######_vidio.jpg', 'Screenshot_20210419-090815_Vidio.jpg', 'y', '', 'y', ''],
    # [    6, 'screenshots#.png', 'Screenshots7.png', '', '', '', ''],
    # [    6, 'the-second-#.jpg', 'THE-SECOND-8.jpg', '', '', '', ''],
    # [    5, '########_######_hdr-pano.jpg', '20160305_144008_HDR-Pano.jpg', 'y', '', 'y', ''],
    # [    5, '####-##-## ##.##.##-edit.dng', '2017-06-29 13.55.01-Edit.dng', 'y', '', 'y', ''],
    # [    5, '####-##-## ##.##.##-pano.jpg', '2017-09-09 17.41.04-Pano.jpg', 'y', '', 'y', ''],
    # [    5, 'create a job #.jpg', 'Create a Job 5.jpg', '', '', '', ''],
    # [    5, 'doodle#.png', 'doodle1.png', '', '', '', ''],
    # [    5, 'droppedimage-#.tiff', 'droppedImage-2.tiff', '', '', '', ''],
    # [    5, 'image (#).png', 'image (3).png', '', '', '', ''],
    # [    5, 'image#.jpg', 'image1.JPG', '', '', '', ''],
    # [    5, 'imgp####_#_#_#_#_tonemapped.jpg', 'IMGP0780_1_2_3_4_tonemapped.jpg', '', '', '', ''],
    # [    5, 'kids conway ##.jpg', 'Kids Conway 03.jpg', '', '', '', ''],
    # [    5, 'meiro-business-segments-#.png', 'meiro-business-segments-6.png', '', '', '', ''],
    # [    5, 'mvp#-##.png', 'mvp1-05.png', '', '', '', ''],
    # [    5, 'pa-####-#.png', 'pa-2022-6.png', '', '', '', ''],
    # [    5, 'photo (#).png', 'photo (4).PNG', '', '', '', ''],
    # [    5, 'signing-#.png', 'signing-5.png', '', '', '', ''],
    # [    5, 'whatsapp image ####-##-## at ##.##.## (#).jpeg', 'WhatsApp Image 2019-08-19 at 21.30.32 (1).jpeg', 'y', '', 'y', ''],
    # [    4, '########_######_hdr-pano.dng', '20160305_144006_HDR-Pano.dng', 'y', '', 'y', ''],
    # [    4, '########_######~#.jpg', '20230429_174851~2.jpg', 'y', '', 'y', ''],
    # [    4, '####-##-##-durian-#.jpg', '2017-08-25-durian-4.jpg', 'y', '', '', ''],
    # [    4, '####-##-##work.jpg', '2013-01-23work.jpg', 'y', '', '', ''],
    # [    4, '###-six-weeks-ncv-#.jpg', '560-six-weeks-ncv-4.jpg', '', '', '', ''],
    # [    4, '##-########_######.jpg', '23-20160414_180742.jpg', 'y', '', 'y', ''],
    # [    4, '#.fig', '1.fig', '', '', '', ''],
    # [    4, '#dofv#-##-l.jpg', '6DOFv2-02-L.jpg', '', '', '', ''],
    # [    4, '#th grade class picture.jpg', '5th Grade Class Picture.jpg', '', '', '', ''],
    # [    4, 'ade-#.png', 'ade-4.png', '', '', '', ''],
    # [    4, 'annboban-#.jpg', 'annboban-4.jpg', '', '', '', ''],
    # [    4, 'aqilliz-#.png', 'aqilliz-4.png', '', '', '', ''],
    # [    4, 'arbitration#.jpg', 'arbitration4.jpg', '', '', '', ''],
    # [    4, 'background-light#.jpg', 'Background-Light5.jpg', '', '', '', ''],
    # [    4, 'bu-intro-#.png', 'bu-intro-5.png', '', '', '', ''],
    # [    4, 'buddah##.jpg', 'buddah50.jpg', '', '', '', ''],
    # [    4, 'c#back.jpg', 'c3back.jpg', '', '', '', ''],
    # [    4, 'chats-loading-#.png', 'chats-loading-4.png', '', '', '', ''],
    # [    4, 'dsc_####.nef', 'DSC_8475.NEF', '', '', '', ''],
    # [    4, 'figure#.jpg', 'figure4.jpg', '', '', '', ''],
    # [    4, 'image_#_#########.jpg', 'image_0_243023844.jpg', '', '', '', ''],
    # [    4, 'img_####-hdr.jpg', 'IMG_3830-HDR.jpg', '', '', '', ''],
    # [    4, 'kitas-##-##.jpeg', 'kitas-16-17.jpeg', '', '', '', ''],
    # [    4, 'lrm_export_###############_########_#########.jpeg', 'LRM_EXPORT_369224610287940_20181114_125252286.jpeg', 'y', '', 'y', ''],
    # [    4, 'photo on ##-#-## at #.## pm.jpg', 'Photo on 12-7-13 at 9.38 PM.jpg', 'y', '', 'y', ''],
    # [    4, 'picture #-#.png', 'Picture 1-1.png', '', '', '', ''],
    # [    4, 'picture_#.jpg', 'Picture_4.jpg', '', '', '', ''],
    # [    4, 'preview.jpg', 'preview.jpg', '', '', '', ''],
    # [    4, 'prom #.jpg', 'Prom 2.JPG', '', '', '', ''],
    # [    4, 'realised#.tif', 'Realised2.tif', '', '', '', ''],
    # [    4, 'screenshot_########-######_tv indonesia online - tv malaysia tv singapore.jpg', 'Screenshot_20210326-172636_TV Indonesia Online - TV Malaysia TV Singapore.jpg', 'y', '', 'y', ''],
    # [    4, 'screenshot_########_######.jpg', 'Screenshot_20221214_183141.jpg', 'y', '', 'y', ''],
    # [    4, 'tk#.jpg.jpg', 'tk4.JPG.jpg', '', '', '', ''],
    # [    4, 'tommy #.jpg', 'Tommy 4.jpg', '', '', '', ''],
    # [    4, 'v#.png', 'V4.png', '', '', '', ''],
    # [    4, 'video-#-##-##-##-##-##-am-converted.mp#', 'Video-6-18-18-10-31-49-AM-converted.mp4', 'y', '', 'y', ''],
    # [    4, 'video-#-##-##-#-##-##-pm-converted.mp#', 'Video-6-18-18-5-19-41-PM-converted.mp4', 'y', '', 'y', ''],
    # [    3, '###################.jpg', '7214229723456342597.jpg', '', '', '', ''],
    # [    3, '#############.jpg', '1513282851309.jpg', 'y', '', 'y', ''],
    # [    3, '##########-#.mp#', '1519447593-2.mp4', 'y', '', 'y', ''],
    # [    3, '####-##-## ##.##.##.jpeg', '2017-09-01 02.19.35.jpeg', 'y', '', 'y', ''],
    # [    3, '####-plan-##.png', '2022-plan-03.png', 'y', '', '', ''],
    # [    3, '####_##_##_##_##_##.mp#', '2019_03_18_14_04_44.mp4', 'y', '', 'y', ''],
    # [    3, '###_####.jpg', '100_0705.JPG', '', '', '', ''],
    # [    3, '##-##-old.png', '05-26-old.png', '', '', '', ''],
    # [    3, 'aaron##.jpg', 'Aaron06.jpg', '', '', '', ''],
    # [    3, 'activated account.png', 'Activated Account.png', '', '', '', ''],
    # [    3, 'advanced filter #-employer.png', 'Advanced filter 3-employer.PNG', '', '', '', ''],
    # [    3, 'ami-standup-#.png', 'ami-standup-4.png', '', '', '', ''],
    # [    3, 'annual-individual-income-tax-return-#.png', 'annual-individual-income-tax-return-4.png', '', '', '', ''],
    # [    3, 'background-dark#.jpg', 'Background-Dark5.jpg', '', '', '', ''],
    # [    3, 'c#front.jpg', 'c4front.jpg', '', '', '', ''],
    # [    3, 'cdn-load-balancing-analytics-tracking-#.png', 'cdn-load-balancing-analytics-tracking-5.png', '', '', '', ''],
    # [    3, 'create company profile #.png', 'Create company profile 3.PNG', '', '', '', ''],
    # [    3, 'create job #.png', 'Create job 3.PNG', '', '', '', ''],
    # [    3, 'document-thumbnail.tiff', 'document-thumbnail.tiff', '', '', '', ''],
    # [    3, 'drbill#.jpg', 'drbill4.jpg', '', '', '', ''],
    # [    3, 'ds-screenshot-#.jpg', 'ds-screenshot-2.jpg', '', '', '', ''],
    # [    3, 'ds-screenshot-#.png', 'ds-screenshot-1.png', '', '', '', ''],
    # [    3, 'email confirmation.png', 'Email Confirmation.png', '', '', '', ''],
    # [    3, 'employer landing page-##.jpg', 'EMployer landing page-03.jpg', '', '', '', ''],
    # [    3, 'f#######_ftyp.mov', 'f0518680_ftyp.mov', '', '', '', ''],
    # [    3, 'flying#.jpg', 'flying3.jpg', '', '', '', ''],
    # [    3, 'geoff##.jpg', 'geoff24.jpg', '', '', '', ''],
    # [    3, 'gnovies-#.png', 'gnovies-3.png', '', '', '', ''],
    # [    3, 'google-deal-#.jpg', 'google-deal-3.jpg', '', '', '', ''],
    # [    3, 'graphic#.png', 'Graphic1.png', '', '', '', ''],
    # [    3, 'harvey hair #.jpg', 'Harvey hair 3.JPG', '', '', '', ''],
    # [    3, 'hiring-echelon-####.###.jpg', 'Hiring-Echelon-2012.003.jpg', 'y', '', '', ''],
    # [    3, 'image#.png', 'image1.png', '', '', '', ''],
    # [    3, 'img_####-pano.dng', 'IMG_3603-Pano.dng', '', '', '', ''],
  ]


  TEST_DATA.each do |count, format, sample, date_format, separator, time_format, regex|
    date_present = !date_format.blank?
    date_format = '' if date_format == 'y'

    time_present = !time_format.blank?
    time_format = '' if time_format == 'y'

    it "#{format} with #{count} examples" do
      msg = [count, format, sample, date_format, separator, time_format, regex].join("\n")

      filename = Filename.new sample

      date_match = filename.date_patterns
      if date_present
        expect(date_match).must_be_instance_of Date
      else
        expect(date_match).must_be_nil("Date Failed on #{date_match} with: #{msg}")
      end

      time_match = filename.time_patterns
      if time_present
        expect(time_match).must_be_instance_of Time
      else
        expect(time_match).must_be_nil("Time Failed on #{time_match} with: #{msg}")
      end

      datetime_match = filename.datetime_patterns
      if date_present && time_present
        expect(datetime_match).must_be_instance_of DateTime
      end
    end

  end
end
